# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6668ae9ad8bcfb839dcba20936bce93a328930b38408fa2aadab8985286a5d4cc303efa628fcaeb161691aa1246c170ae67a41fc7d227ef7a9ed83936f10ef26

test:
  secret_key_base: 0a6f274129b2b3029da514fa7aefa3fecec8ac19873b86d7b3e39161b2f1fd3c8686f267e5fe1b0b2667becc08c464a3c2693657bbf39cbb382519588b477a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
